---
services:

  # Graph database storing scene graph
  neo4j:
    image: neo4j:5.25.1
    environment:
      NEO4J_server_bolt_listen__address: :7683
      NEO4J_server_http_advertised__address: :7469
      NEO4J_server_http_listen__address: :7469
      NEO4J_AUTH: neo4j/neo4j_pw
    ports: [7683:7683, 7469:7469]
    healthcheck:
      test: [CMD-SHELL, wget --no-verbose --tries=1 --spider http://localhost:7469 || exit 1]
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 2s
    networks:
      - heracles_net

  # Standalone python interpreter example for running queries against database
  cli:
    build:
      context: ..
      dockerfile: docker/minimal_db_cli.Dockerfile
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      HERACLES_NEO4J_USERNAME: neo4j
      HERACLES_NEO4J_PASSWORD: neo4j_pw
      HERACLES_NEO4J_URI: neo4j://neo4j:7683
    networks: [heracles_net]
    stdin_open: true
    tty: true
    entrypoint: [ipython, -i, /heracles/examples/load_scene_graph.py, --, --scene_graph, /heracles/examples/scene_graphs/example_dsg.json]

  # Interactive LLM-based agent interaction with database
  chatdsg:
    build:
      context: ..
      dockerfile: docker/chatdsg_demo.Dockerfile
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      HERACLES_NEO4J_USERNAME: neo4j
      HERACLES_NEO4J_PASSWORD: neo4j_pw
      HERACLES_NEO4J_URI: neo4j://neo4j:7683
      HERACLES_OPENAI_API_KEY: $HERACLES_OPENAI_API_KEY
      HERACLES_AGENTS_PATH: /heracles_agents
    networks: [heracles_net]
    extra_hosts: [host.docker.internal:host-gateway]
    stdin_open: true
    tty: true
    entrypoint: [python3, chatdsg.py, --scene-graph, /example_dsg.json]

  # Visualize scene graph in RVIZ using Hydra ROS visualizer
  hydra_visualization:
    image: aaronraymit/hydra_visualizer:v0.1
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      HERACLES_NEO4J_USERNAME: neo4j
      HERACLES_NEO4J_PASSWORD: neo4j_pw
      HERACLES_IP: neo4j
      HERACLES_PORT: 7683
      HERACLES_VENV: ''
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
    networks: [heracles_net]
    volumes: [/tmp/.X11-unix:/tmp/.X11-unix:rw]
    entrypoint: [/bin/bash, /run_hydra_visualization.sh]

  # Visualize scene graph in Viser using spark_dsg Viser visualization
  viser_visualization:
    build:
      context: ..
      dockerfile: docker/spark_dsg_viser.Dockerfile
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      HERACLES_NEO4J_USERNAME: neo4j
      HERACLES_NEO4J_PASSWORD: neo4j_pw
      HERACLES_NEO4J_URI: neo4j://neo4j:7683
    networks: [heracles_net]
    ports: [8081:8081]
    entrypoint: [python, /heracles/src/heracles/heracles_viser_publisher.py, --ip, 0.0.0.0, --port, '8081', --uri, neo4j://neo4j:7683]
networks:
  heracles_net:
    driver: bridge
