---
/**:
  ros__parameters:
    heracles_ip: $(env ADT4_HERACLES_IP)
    heracles_port: $(env ADT4_HERACLES_PORT)
    map_frame: map
    robot_name: $(var robot_name)
    robot_names: ['']  # several robots, e.g. on a base station
    publish_rate: 1.0
